/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.view.panel;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import main.controller.CommandeController;
import main.controller.ProduitController;
import main.model.entite.Commande;
import main.model.entite.Produit;
import main.model.dao.CommandeDAO;

/**
 *
 * @author Ali Barry
 */
public class CommandePanel extends javax.swing.JPanel {
    private final CommandeController commandeController;
    private final ProduitController produitController;
    private DefaultTableModel modelLignes; // tableau temporaire des produits ajoutés
    private javax.swing.JTable lignesTable; 
    /**
     * Creates new form CommandePanel
     */
    public CommandePanel() {
        initComponents();
        commandeController = new CommandeController();
        produitController  = new ProduitController();

        chargerProduitsDansCombo();
        initialiserTableauLignes();
        chargerCommandes();
        appliquerStyleTableau();
        
        vider.addActionListener(e -> viderFormulaire());
        validerlignecommande.addActionListener(e -> ajouterLigneCommande());
        rechercher.addActionListener(e -> rechercherCommande());
        
        jPanel1.validate();
        jPanel2.repaint();
        
        jSpinner1.setValue(1);
        
        //JSpinner.DateEditor editor = new JSpinner.DateEditor(jSpinner2, "yyyy-MM-dd");
        //jSpinner2.setEditor(editor);
        
        //((JSpinner.DefaultEditor) jSpinner2.getEditor()).getTextField().setEditable(false);

        
        cmdTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        cmdTable.getTableHeader().setBackground(Color.BLUE); // Ton vert
        cmdTable.getTableHeader().setForeground(java.awt.Color.BLACK);
        cmdTable.setRowHeight(50); 
        cmdTable.setSelectionBackground(new java.awt.Color(51, 153, 255)); 

            
        cmdTable.setShowGrid(false);
        cmdTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        cmdTable.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));

        
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        
        for (int i = 0; i < cmdTable.getColumnCount(); i++) {
            cmdTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        
        cmdTable.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        vider = new javax.swing.JButton();
        validerlignecommande = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        selectedProd = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cmdTable = new javax.swing.JTable();
        rechercher = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setBackground(new java.awt.Color(204, 204, 204));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1548, 1327));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("GESTION COMMANDES");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("PASSER UNE COMMANDE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Produits Sélectionnées :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Sélectinner le produit :");

        jButton1.setBackground(new java.awt.Color(35, 166, 97));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("COMMANDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Etat de la commande :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VALIDEE", "EN_COURS", "ANNULEE" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Total :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Quantité de produit :");

        vider.setBackground(new java.awt.Color(153, 153, 153));
        vider.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vider.setText("vider");
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });

        validerlignecommande.setBackground(new java.awt.Color(0, 153, 153));
        validerlignecommande.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        validerlignecommande.setText("valider");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Date Commande :");

        jSpinner2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.ERA));

        selectedProd.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(validerlignecommande, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinner1)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, 329, Short.MAX_VALUE))))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(selectedProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectedProd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validerlignecommande, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jToggleButton2.setBackground(new java.awt.Color(255, 102, 102));
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton2.setText("Supprimer");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        cmdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NUMERO DE LA COMMANDE", "DATE DE LA COMMANDE", "STATUS", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(cmdTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        rechercher.setBackground(new java.awt.Color(153, 153, 153));
        rechercher.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rechercher.setText("rechercher");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        supprimerCommande();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        validerCommandeComplete();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cmdTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton rechercher;
    private javax.swing.JLabel selectedProd;
    private javax.swing.JButton validerlignecommande;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables


   
    private void chargerProduitsDansCombo() {
        jComboBox2.removeAllItems();
        List<Produit> produits = produitController.obtenirTousProduits();
        for (Produit p : produits) {
            jComboBox2.addItem(p.getNom());
        }
    }

   
    private Produit getProduitSelectionne() {
        int index = jComboBox2.getSelectedIndex();
        if (index == -1) return null;
        return produitController.obtenirTousProduits().get(index);
    }

    
    private void initialiserTableauLignes() {
    modelLignes = new DefaultTableModel(
        new String[]{"idProd", "Produit", "Prix Unitaire", "Quantité", "Sous-total"},
        0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    lignesTable = new javax.swing.JTable(modelLignes);
    lignesTable.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    lignesTable.setRowHeight(30);
    lignesTable.setShowGrid(true);
    lignesTable.setGridColor(Color.LIGHT_GRAY);

    
    lignesTable.getColumnModel().getColumn(0).setMinWidth(0);
    lignesTable.getColumnModel().getColumn(0).setMaxWidth(0);
    lignesTable.getColumnModel().getColumn(0).setWidth(0);

    javax.swing.JScrollPane scrollLignes = new javax.swing.JScrollPane(lignesTable);
    scrollLignes.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GRAY));


    
    jTextField3.setText("0.00 FCFA");
    jTextField3.setEditable(false);
    jTextField3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
}

    
    private void chargerCommandes() {
        try {
            List<Commande> commandes = commandeController.getAllCommandes();

            DefaultTableModel model = new DefaultTableModel(
                new String[]{"idCom", "NUMERO", "DATE", "STATUS", "TOTAL"},
                0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            for (Commande c : commandes) {
                model.addRow(new Object[]{
                    c.getIdCom(),
                    c.getIdCom(),
                    c.getDateCommande(),
                    c.getEtat().name(),
                    String.format("%.2f FCFA", c.getTotalCommande())
                });
            }

            cmdTable.setModel(model);

            // Cacher idCom
            cmdTable.getColumnModel().getColumn(0).setMinWidth(0);
            cmdTable.getColumnModel().getColumn(0).setMaxWidth(0);
            cmdTable.getColumnModel().getColumn(0).setWidth(0);

            appliquerStyleTableau();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erreur chargement commandes : " + e.getMessage(),
                "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    
    private void ajouterLigneCommande() {
        try {
            Produit produit = getProduitSelectionne();

            if (produit == null) {
                JOptionPane.showMessageDialog(this,
                    "Veuillez sélectionner un produit",
                    "Aucun produit", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int quantite = (Integer) jSpinner1.getValue();
            if (quantite <= 0) {
                JOptionPane.showMessageDialog(this,
                    "La quantité doit être supérieure à 0",
                    "Quantité invalide", JOptionPane.WARNING_MESSAGE);
                return;
            }

            
            for (int i = 0; i < modelLignes.getRowCount(); i++) {
                if (modelLignes.getValueAt(i, 0).equals(produit.getIdProd())) {
                    JOptionPane.showMessageDialog(this,
                        "Ce produit est déjà dans la commande",
                        "Doublon", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            double sousTotal = produit.getPrixVente() * quantite;

            modelLignes.addRow(new Object[]{
                produit.getIdProd(),
                produit.getNom(),
                produit.getPrixVente(),
                quantite,
                sousTotal
            });

            mettreAJourTotal();
            jSpinner1.setValue(1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erreur : " + e.getMessage(),
                "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        mettreAJourLabelProduits();

    }

    
    private void validerCommandeComplete() {
        try {
            if (modelLignes.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                    "Ajoutez au moins un produit avant de commander",
                    "Commande vide", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int confirmation = JOptionPane.showConfirmDialog(this,
                "Confirmer la commande ? Le stock sera mis à jour.",
                "Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirmation != JOptionPane.YES_OPTION) return;

            
            String idCom = commandeController.creerCommande().getIdCom();

            
            for (int i = 0; i < modelLignes.getRowCount(); i++) {
                String idProd = String.valueOf(modelLignes.getValueAt(i, 0));
                double prix   = (double) modelLignes.getValueAt(i, 2);
                int qte       = (int)    modelLignes.getValueAt(i, 3);
                commandeController.ajouterProduitCommande(idCom, idProd, qte, prix);
            }

            
            commandeController.validerCommande(idCom);

            JOptionPane.showMessageDialog(this,
                "Commande validée avec succès ! Stock mis à jour.",
                "Succès", JOptionPane.INFORMATION_MESSAGE);

            viderFormulaire();
            chargerCommandes();

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Erreur métier", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erreur : " + e.getMessage(),
                "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    
    private void viderFormulaire() {
        modelLignes.setRowCount(0);
        jTextField3.setText("0.00 FCFA");
        jSpinner1.setValue(1);
        if (jComboBox2.getItemCount() > 0) jComboBox2.setSelectedIndex(0);
    }

    
    private void supprimerCommande() {
        try {
            int selectedRow = cmdTable.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this,
                    "Veuillez sélectionner une commande",
                    "Aucune sélection", JOptionPane.WARNING_MESSAGE);
                jToggleButton2.setSelected(false);
                return;
            }

            String statut = String.valueOf(cmdTable.getValueAt(selectedRow, 3));
            if ("VALIDEE".equals(statut)) {
                JOptionPane.showMessageDialog(this,
                    "Impossible de supprimer une commande déjà validée",
                    "Suppression impossible", JOptionPane.ERROR_MESSAGE);
                jToggleButton2.setSelected(false);
                return;
            }

            String idCom = String.valueOf(cmdTable.getValueAt(selectedRow, 0));

            int confirmation = JOptionPane.showConfirmDialog(this,
                "Voulez-vous vraiment supprimer cette commande ?",
                "Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirmation == JOptionPane.YES_OPTION) {
                Commande cmd = commandeController.getCommandeById(idCom);
                CommandeDAO dao = new CommandeDAO();
                boolean ok = dao.delete(cmd);

                if (ok) {
                    JOptionPane.showMessageDialog(this,
                        "Commande supprimée avec succès !",
                        "Succès", JOptionPane.INFORMATION_MESSAGE);
                    chargerCommandes();
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Erreur lors de la suppression",
                        "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }

            jToggleButton2.setSelected(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erreur : " + e.getMessage(),
                "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    
    private void rechercherCommande() {
        String terme = jTextField1.getText().trim().toLowerCase();
        try {
            List<Commande> toutes = commandeController.getAllCommandes();
            DefaultTableModel model = (DefaultTableModel) cmdTable.getModel();
            model.setRowCount(0);

            for (Commande c : toutes) {
                if (terme.isEmpty() || c.getIdCom().toLowerCase().contains(terme)
                        || c.getEtat().name().toLowerCase().contains(terme)) {
                    model.addRow(new Object[]{
                        c.getIdCom(),
                        c.getIdCom(),
                        c.getDateCommande(),
                        c.getEtat().name(),
                        String.format("%.2f FCFA", c.getTotalCommande())
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erreur : " + e.getMessage(),
                "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void mettreAJourTotal() {
        double total = 0;
        for (int i = 0; i < modelLignes.getRowCount(); i++) {
            total += (double) modelLignes.getValueAt(i, 4);
        }
        jTextField3.setText(String.format("%.2f FCFA", total));
    }

    
    private void appliquerStyleTableau() {
        cmdTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        cmdTable.getTableHeader().setBackground(Color.BLUE);
        cmdTable.getTableHeader().setForeground(java.awt.Color.BLACK);
        cmdTable.setRowHeight(50);
        cmdTable.setSelectionBackground(new java.awt.Color(51, 153, 255));
        cmdTable.setShowGrid(false);
        cmdTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        cmdTable.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));

        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < cmdTable.getColumnCount(); i++) {
            cmdTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        jScrollPane3.setBorder(null);
    }
    
    private void modifierEtatCommande() {
    try {
        int selectedRow = cmdTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Sélectionnez une commande",
                "Aucune sélection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idCom = String.valueOf(cmdTable.getValueAt(selectedRow, 0));
        String nouvelEtat = (String) jComboBox1.getSelectedItem();

        commandeController.modifierEtatCommande(idCom, nouvelEtat);

        JOptionPane.showMessageDialog(this,
            "Etat modifié avec succès",
            "Succès",
            JOptionPane.INFORMATION_MESSAGE);

        chargerCommandes();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Erreur : " + e.getMessage(),
            "Erreur",
            JOptionPane.ERROR_MESSAGE);
    }
}

private void mettreAJourLabelProduits() {
    StringBuilder sb = new StringBuilder();

    for (int i = 0; i < modelLignes.getRowCount(); i++) {
        String nom = String.valueOf(modelLignes.getValueAt(i, 1));
        int qte = (int) modelLignes.getValueAt(i, 3);

        sb.append(nom)
          .append(" x")
          .append(qte);

        if (i < modelLignes.getRowCount() - 1) {
            sb.append(" | ");
        }
    }

    selectedProd.setText(sb.toString());
}


}
