/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.view.panel;

import java.awt.BorderLayout;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Ali Barry
 */
public class StatistiquePanel extends javax.swing.JPanel {
    private String userEmail;
    /**
     * Creates new form StatistiquePanel
     */
    public StatistiquePanel(String email) {
        initComponents();
        this.userEmail = email;
        setLayout(new BorderLayout()); // Important pour que le graphique occupe tout l'espace
        
        afficherGraphiqueVentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1252, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void afficherGraphiqueVentes() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        
        // Exemple de données statiques (à remplacer par un appel Controller)
        dataset.setValue("Pizzas", 450.0);
        dataset.setValue("Boissons", 120.5);
        dataset.setValue("Desserts", 85.0);
        dataset.setValue("Entrées", 150.0);

        // 2. Créer le graphique
        JFreeChart chart = ChartFactory.createPieChart(
                "Répartition des Ventes par Catégorie", // Titre
                dataset,                               // Données
                true,                                  // Légende
                true,                                  // Tooltips
                false                                  // URLs
        );

        // 3. Mettre le graphique dans un Panel spécialisé JFreeChart
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(600, 400));
        
        // 4. Ajouter au StatistiquePanel
        this.add(chartPanel, BorderLayout.CENTER);
        this.revalidate(); // Rafraîchit l'affichage
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
